[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_escrow = "GT2xcgeotPZzzgb924oUh1zvEU4WBkrfkk2WP86UBdE7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
